### ISSUE TITLE
DSE logic is repeated in extra monitor

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/SpiNNFrontEndCommon#659]
having reviewed this again. i laded on this AGAIN, and i still think (and @rowleya also thinks) that we shouldn't be bringing this in as a clone. we should adjust the dsg code accordingly. either by not using logs in it, or having 2 version which have the different types of print so you can import the right one. ill leave the other pointers of this block resolved, but the overarching issue still needs thought.

_Originally posted by @alan-stokes in https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/583#discussion_r486212451_

**Comment by dkfellows** [comment]
I'm not opposed to fixing that. It's just off-topic for #583

**Comment by alan-stokes** [comment]
fair

**Comment by Christian-B** [comment]
@alan-stokes claims @rowleya knows what is is about

**Comment by rowleya** [comment]
I believe this issue is that the DSG constant is repeated in two places, so I have renamed the ticket.  I think the problem is that the DSE brings in spin1 API but the extra monitor doesn't want this.  Hence the DSE code would need to be examined to check where it uses the spin1 API.  I don't think it really needs it, but I could be wrong!

**Comment by dkfellows** [comment]
OK, if it is tangled up with the special setup of the extra monitor then it can stay as it is.
